version: "3"
services:
  backend:
    container_name: amablog-backend
    restart: always
    build: backend
    ports:
      - 3000:80
    links:
      - mongo
  mongo:
    container_name: amablog-mongo
    image: mongo
    ports:
      - "27017:27017"