version: "3"
services:
  backend:
    container_name: amablog-backend
    restart: always
    build: backend
    links:
      - mongo
    environment:
      - MONGO_DATABASE=amablog
      - ACCESS_TOKEN_SECRET
  mongo:
    container_name: amablog-mongo
    image: mongo
  nginx:
    image: nginx:1.19.4-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
