version: "3"
services:
  backend:
    container_name: amablog-backend
    restart: always
    build: backend
    links:
      - mongo
    environment:
      - MONGO_DATABASE=amablog
      - ACCESS_TOKEN_SECRET
  mongo:
    container_name: amablog-mongo
    image: mongo
