version: "3"
services:
  backend:
    container_name: amablog-backend
    restart: always
    build: backend
    links:
      - mongo
    volumes: 
      - ./backend/src:/app/src
    environment:
      - MONGO_DATABASE=amablog
      - ACCESS_TOKEN_SECRET
  mongo:
    container_name: amablog-mongo
    image: mongo
    volumes:
      - ./db-data:/data/db
  nginx:
    container_name: amablog-nginx
    image: nginx:1.19.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/mnt/frontend:ro
      - $FULLCHAIN_PATH:/etc/ssl-files/fullchain.pem:ro
      - $PRIVKEY_PATH:/etc/ssl-files/privkey.pem:ro
    depends_on:
      - backend
